import Head from 'next/head'
import Image from 'next/image';
import Link from 'next/link';
import { LinkArrow } from '@/components/icons';
import { Inter } from 'next/font/google'
import Layout from '@/components/Layout'
import profilePic from "../../public/images/profile/developer-pic-1.png";
import AnimatedText from '@/components/AnimatedText';
import TransitionEffect from '@/components/hooks/TransitionEffect';
import ContactForm from '@/components/ContactForm';


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />

      </Head>
      <TransitionEffect />
      <main className="flex items-center text-dark w-full min-h-screen dark:text-light ">
      <Layout className='pt-0 md:pt-16 sm:pt-8'>
        <div className="flex items-center justify-between w-full lg:flex-col">
          <div className='w-1/2 md:w-full'>
            <Image src={profilePic} alt="developer image" className="w-full h-auto md:inline-block md:w-full" 
            priority
            sizes='(max-width: 768px) 100vw, (max-width:1200px) 50vw, 
            50vw'
            />
          </div>
          <div className='w-1/2 flex flex-col items-center self-center lg:w-full lg:text-center'>
            <AnimatedText text="Turning your ideas into Reality with Code and Design." className='!text-6xl !text-left
            xl:!text-5xl lg:!text-center lg:!text=6xl md:!text-5xl sm:!text-4xl' />
            <p className='my-4 text-base font-medium'>As a skilled full-stack developer, I am dedicated to turning ideas into innovate products. 
              Check out this site to see my latest projects and articles. </p> 
              <div className='flex items-center self-start mt-2 lg:self-center'>
            <Link href="/dummy.pdf" target={"_blank"}
            className='flex items-center bg-dark text-light p-2.5 px-6 rounded-lg text-lg font-semibold hover:bg-light hover:text-dark
            border-2 border-solid border-transparent hover:border-dark dark:bg-light dark:text-dark
            '
            download={true}
            >CV <LinkArrow className="w-6 ml-1" /></Link>
            <Link href="mailto:mlynagh111@gmail.com" 
            className='ml-4 text-lg font-medium capitalize text-dark underline dark:text-light'
            >Contact </Link>
          </div>
          </div>
          
        </div>
        <ContactForm />
      </Layout>

      </main>
    </>
  )
}
